Repository Ham-Protocol/ham-protocol, pull requests merged in 2020-09, with the labels that each got.

#39 Improve color objects
  ham-www/src/components/Button/Button.tsx
  ham-www/src/components/Card/Card.tsx
  ham-www/src/components/CardIcon/CardIcon.tsx
  ham-www/src/components/Dial/Dial.tsx
  ham-www/src/components/Footer/components/Nav.tsx
  ham-www/src/components/IconButton/IconButton.tsx
  ham-www/src/components/Input/Input.tsx
  ham-www/src/components/Label/Label.tsx
  ham-www/src/components/Loader/Loader.tsx
  ham-www/src/components/Logo/Logo.tsx
  ham-www/src/components/Modal/Modal.tsx
  ham-www/src/components/ModalActions/ModalActions.tsx
  ham-www/src/components/ModalTitle/ModalTitle.tsx
  ham-www/src/components/PageHeader/PageHeader.tsx
  ham-www/src/components/StepProgressBar/StepProgressBar.tsx
  ham-www/src/components/TokenInput/TokenInput.tsx
  ham-www/src/components/TopBar/components/AccountModal.tsx
  ham-www/src/components/TopBar/components/Nav.tsx
  ham-www/src/components/TopBar/components/ThemeToggle.tsx
  ham-www/src/components/Value/Value.tsx
  ham-www/src/components/icons/AddIcon.tsx
  ham-www/src/components/icons/RemoveIcon.tsx
  ham-www/src/contexts/Modals/Modals.tsx
  ham-www/src/theme/colors.ts
  ham-www/src/views/Farms/components/FarmCards.tsx
  ham-www/src/views/Home/Home.tsx
  ham-www/src/views/Home/components/Rebase.tsx
  ham-www/src/views/Home/components/Stats.tsx
  ham-www/src/views/Home/components/Vote.tsx
  ham-www/src/wrapping/WrappedStatusToggle.tsx
Labels: enhancement, front-end

#41 Improve pink theme
  ham-www/src/theme/colors.ts
Labels: design, front-end

#44 Fix size and paddings of pig icon in the switch
  ham-www/src/components/TopBar/components/ThemeToggle.tsx
Labels: front-end

#38 Harvestable HAMs in Farms view
  ham-www/package-lock.json
  ham-www/src/utils/index.ts
  ham-www/src/views/Farms/components/FarmCards.tsx
Labels: front-end
